play_motion:

  motions:
    safe_unfold:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 1.0
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 2.0
      - positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 3.5
      - positions: [0.30, 0.0, -0.0, -0.00, 0.0, 0.00, -0.0, 0.00]
        time_from_start: 4.5
      - positions: [0.35, 0.05, 0, -1.62, 0.0, 0.05, -0.0, 0.00]
        time_from_start: 5.5


      meta:
        name: Safe unfold
        usage: ECR_comp
        description: 'unfold the arm close to the body to a raised position'

         
        
    arm_out:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 1.0


      meta:
        name: Extend arm
        usage: ECR_comp
        description: 'unfold the arm to hand over an object to a user'







